version: '3.9'

services:
    app:
      build:
        dockerfile: ./Dockerfile
        context: .
      environment:
        SQLALCHEMY_DATABASE_URI: postgresql://user:password@pg:5432/blog
        CONFIG_NAME: DevConfig
      volumes:
      - ./blog:/app/blog
      ports:
        - '5000:5000'
      depends_on:
        pg:
          condition: service_healthy
    pg:
      image: postgres:13.1
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d blog -U user"]
        interval: 5s
        timeout: 10s
        retries: 10
      privileged: true
      environment:
        POSTGRES_DB: blog
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      volumes:
      - pgdata:/var/lib/postgresql/data
      ports:
        - '5432:5432'


volumes:
  pgdata: